#ifndef DRAGON_ALPHA_1_0_CODE_DESIGN_RUNTIME_GENERATED_H
#define DRAGON_ALPHA_1_0_CODE_DESIGN_RUNTIME_GENERATED_H

// Auto-generated from Resources/Config/RuntimeDesign.cfg by GenerateDesignHeaders.sh.
// Edit the design config and regenerate instead of changing this file directly.

#define DESIGN_GAME_NAME "Dragon Alpha"
#define DESIGN_COMPANION_BUNDLE_ID "com.Dracosoft.EpicDragon"
#define DESIGN_FULL_GAME 0

#define DESIGN_BASE_WIDTH 800
#define DESIGN_BASE_HEIGHT 600

#define DESIGN_PREFERRED_WIDTH 1920
#define DESIGN_PREFERRED_HEIGHT 1080

#define DESIGN_ENABLE_REAL_MONEY_STORE 0
#define DESIGN_ENABLE_ADS 0
#define DESIGN_ENABLE_ANALYTICS 0
#define DESIGN_ENABLE_AUDIO 1
#define DESIGN_USE_SAFE_AREA 1

#define DESIGN_UNLOCK_AVATAR_COST 25
#define DESIGN_UNLOCK_CATEGORY_COST 50
#define DESIGN_UNLOCK_PREMIUM_CATEGORY_COST 300
#define DESIGN_TRAINING_BASE_COST 100
#define DESIGN_STARTING_GOLD 500
#define DESIGN_MAX_GOLD 999999999
#define DESIGN_MAX_TOKENS 999999999
#define DESIGN_STARTING_TOKENS_FULL 300
#define DESIGN_STARTING_TOKENS_LITE 25
#define DESIGN_SPLASH_MIN_MILLISECONDS 2000
#define DESIGN_MENU_CARD_GAP 28
#define DESIGN_BATTLE_PREVIEW_PULSE_MS 800
#define DESIGN_SHOW_LEGACY_HINTS 1
#define DESIGN_TRAVERSAL_SFX_ENABLED 0
#define DESIGN_TRAVERSAL_SFX_STEP_VARIANTS 1
#define DESIGN_TRAVERSAL_SFX_BUMP_COOLDOWN_MS 180

#endif // DRAGON_ALPHA_1_0_CODE_DESIGN_RUNTIME_GENERATED_H
