#ifndef DRAGON_ALPHA_LEGACY_SCRIPT_DATA_GENERATED_H
#define DRAGON_ALPHA_LEGACY_SCRIPT_DATA_GENERATED_H

// Auto-generated by Agents/GenerateLegacyScriptData.sh
// Source: Assets/Legacy/Data/Areas/*/Data (Map/Obj/Text resources)

#include <stdint.h>
#include <stddef.h>

struct DragonLegacyMapObject {
	uint16_t type;
	uint16_t x1;
	uint16_t y1;
	uint16_t x2;
	uint16_t y2;
	uint16_t data0;
	uint16_t data1;
	uint16_t data2;
	uint16_t data3;
};

struct DragonLegacyObjectResource {
	uint16_t id;
	DragonLegacyMapObject object;
};

struct DragonLegacyTextEntry {
	uint16_t id;
	const char* text;
};

struct DragonLegacyMapScriptData {
	uint16_t pluginId;
	uint16_t mapId;
	const char* mapName;
	int objectCount;
	const DragonLegacyMapObject* objects;
	int textCount;
	const DragonLegacyTextEntry* texts;
	int objectResourceCount;
	const DragonLegacyObjectResource* objectResources;
	uint16_t randomBattles[16];
	uint16_t rareBattles[4];
};

static const DragonLegacyTextEntry kDragonLegacyTexts_1[] = {
	{128, "We are here to help defend against the dragons.  We could always use another strong hand."},
	{129, "A lot of dragons have been attacking from the mountains to the north.  I would avoid them until you get really strong."},
	{130, "Arr, have a drink."},
	{131, "Auuhh...  I cou..ld walllk a straight... line... sure..."},
	{132, "Let me drink in peace."},
	{133, "Rest and heal your wounds."},
	{134, "..."},
	{135, "..."},
	{136, "Would you like to test your skills against the tip of my spear?"},
	{137, "If you don't tell my boss, I have rare items I can sell you."},
	{138, "Only the Lord of Eleusis Stronghold can unlock this door."},
	{139, "My husband wants his daughters to grow up and get married so that maybe there will be more male influence around the castle."},
	{140, "My Daddy killed a dragon with and fork then ate it!"},
	{141, "My dad is bigger than your dad."},
	{142, "I'm very impressed.  I have unlocked my treasure vault for you.  I hear rumor that Goblins have taken over the town of Titanium to the east.  I'm sure they could use your help."},
	{143, "Our stronghold is having troubles fending of the goblins in the caves.  If only someone could bring me the head of their leader I would open my treasure vault to them."},
};

static const DragonLegacyObjectResource kDragonLegacyObjectResources_1[] = {
	{128, {8, 0, 0, 0, 0, 0, 0, 0, 0}},
	{129, {12, 0, 0, 0, 0, 0, 128, 0, 0}},
	{130, {10, 0, 0, 0, 0, 0, 130, 0, 0}},
	{131, {7, 0, 0, 0, 0, 3, 102, 2, 128}},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_1_128[] = {
	{1, 25, 16, 25, 16, 1, 129, 12, 19},
	{1, 38, 6, 46, 6, 3, 128, 42, 55},
	{1, 9, 32, 9, 36, 4, 129, 73, 29},
	{1, 30, 37, 33, 37, 4, 132, 42, 7},
	{1, 79, 25, 79, 25, 2, 128, 63, 5},
	{2, 10, 32, 10, 36, 0, 0, 0, 0},
	{2, 30, 36, 33, 36, 0, 0, 0, 0},
	{1, 19, 21, 19, 21, 1, 128, 5, 62},
	{1, 5, 63, 5, 63, 1, 128, 19, 21},
	{1, 15, 27, 15, 27, 1, 128, 25, 62},
	{1, 25, 63, 52, 63, 1, 128, 15, 27},
	{1, 25, 33, 25, 33, 1, 128, 47, 62},
	{1, 47, 63, 47, 63, 1, 128, 25, 33},
	{1, 38, 22, 38, 22, 1, 128, 69, 62},
	{1, 69, 63, 69, 63, 1, 128, 38, 22},
	{1, 38, 34, 38, 34, 1, 128, 79, 46},
	{1, 79, 47, 79, 47, 1, 128, 38, 34},
	{1, 49, 16, 49, 16, 1, 128, 79, 12},
	{1, 78, 13, 80, 13, 1, 128, 48, 16},
	{1, 79, 7, 79, 7, 1, 128, 78, 29},
	{1, 78, 30, 78, 30, 1, 128, 79, 7},
	{5, 23, 17, 23, 17, 0, 128, 0, 0},
	{5, 27, 17, 27, 17, 0, 129, 0, 0},
	{10, 5, 58, 5, 58, 0, 128, 0, 0},
	{10, 25, 58, 25, 58, 0, 129, 0, 0},
	{5, 47, 55, 47, 56, 0, 130, 0, 0},
	{5, 42, 57, 42, 57, 0, 131, 0, 0},
	{5, 48, 57, 48, 57, 0, 132, 0, 0},
	{5, 66, 61, 67, 61, 0, 133, 0, 128},
	{3, 0, 0, 0, 0, 1, 128, 78, 39},
	{11, 78, 39, 78, 39, 1, 128, 1, 0},
	{3, 0, 0, 0, 0, 2, 128, 79, 39},
	{11, 79, 39, 79, 39, 2, 129, 2, 0},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_1_129[] = {
	{1, 11, 19, 13, 19, 1, 128, 25, 16},
	{1, 5, 17, 5, 18, 2, 128, 3, 17},
	{1, 20, 17, 20, 18, 2, 128, 22, 17},
	{1, 23, 7, 23, 7, 1, 129, 81, 16},
	{1, 81, 16, 81, 16, 1, 129, 23, 7},
	{1, 81, 5, 81, 5, 1, 129, 23, 60},
	{1, 23, 60, 23, 60, 1, 129, 81, 5},
	{5, 11, 2, 11, 2, 0, 134, 0, 0},
	{5, 14, 2, 14, 2, 0, 135, 0, 0},
	{9, 15, 9, 15, 9, 0, 0, 0, 0},
	{6, 20, 12, 20, 12, 0, 136, 129, 0},
	{5, 73, 11, 73, 11, 0, 137, 0, 130},
	{5, 74, 13, 74, 13, 0, 138, 0, 0},
	{3, 0, 0, 0, 0, 3, 129, 75, 10},
	{4, 75, 10, 75, 13, 3, 0, 0, 0},
	{11, 79, 11, 79, 11, 0, 130, 0, 0},
	{3, 0, 0, 0, 0, 4, 128, 76, 15},
	{11, 76, 15, 76, 15, 4, 131, 4, 0},
	{3, 0, 0, 0, 0, 5, 128, 77, 15},
	{11, 77, 15, 77, 15, 5, 132, 5, 0},
	{5, 9, 47, 9, 47, 0, 139, 0, 0},
	{5, 6, 55, 6, 55, 0, 140, 0, 0},
	{5, 5, 60, 5, 60, 0, 141, 0, 0},
	{5, 12, 1, 13, 1, 0, 142, 0, 0},
	{5, 12, 1, 13, 1, 3, 143, 0, 131},
};

static const DragonLegacyTextEntry kDragonLegacyTexts_2[] = {
	{128, "Me not let you get to leader.  Me crush your bones."},
	{129, "NONE SHALL PASS."},
	{130, "You think you can defeat me?  We'll see."},
	{131, "I... should have... known... my mas..ter...  will... destroy... you and..."},
};

static const DragonLegacyObjectResource kDragonLegacyObjectResources_2[] = {
	{128, {12, 0, 0, 0, 0, 0, 1001, 0, 0}},
	{129, {12, 0, 0, 0, 0, 0, 1002, 0, 0}},
	{130, {12, 0, 0, 0, 0, 0, 1003, 0, 131}},
	{131, {5, 0, 0, 0, 0, 0, 131, 0, 0}},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_2_128[] = {
	{1, 4, 17, 4, 18, 1, 129, 5, 17},
	{1, 21, 17, 21, 18, 1, 129, 20, 17},
	{1, 63, 4, 63, 4, 1, 128, 79, 25},
	{3, 0, 0, 0, 0, 6, 200, 7, 54},
	{3, 0, 0, 0, 0, 7, 200, 56, 59},
	{3, 0, 0, 0, 0, 8, 201, 63, 17},
	{3, 0, 0, 0, 0, 9, 202, 66, 50},
	{3, 0, 0, 0, 0, 10, 203, 66, 54},
	{3, 0, 0, 0, 0, 11, 204, 72, 52},
	{11, 7, 54, 7, 54, 6, 128, 6, 0},
	{11, 56, 59, 56, 59, 7, 129, 7, 0},
	{12, 63, 17, 63, 17, 8, 1000, 8, 0},
	{5, 66, 50, 66, 50, 9, 128, 9, 128},
	{5, 66, 54, 66, 54, 10, 129, 10, 129},
	{5, 72, 52, 72, 52, 11, 130, 11, 130},
};

static const DragonLegacyTextEntry kDragonLegacyTexts_3[] = {
	{128, "Who dares to destroy my masters creation.  You shall not live to boast about your victory."},
	{129, "You have no idea what you have unleashed..  This world will now suffer a fate far beyond hell itself...  My masters anger will consume your very being...  For he was the one who unleashed this dragon plague upon this world..."},
};

static const DragonLegacyObjectResource kDragonLegacyObjectResources_3[] = {
	{128, {5, 0, 0, 0, 0, 0, 128, 0, 129}},
	{129, {12, 0, 0, 0, 0, 0, 129, 0, 130}},
	{130, {5, 0, 0, 0, 0, 0, 129, 0, 0}},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_3_128[] = {
	{1, 39, 6, 42, 6, 3, 129, 42, 55},
	{1, 41, 56, 44, 56, 1, 128, 42, 7},
	{1, 67, 38, 67, 44, 1000, 128, 10, 32},
	{3, 0, 0, 0, 0, 0, 128, 66, 31},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_3_129[] = {
	{1, 39, 6, 42, 6, 3, 130, 42, 55},
	{1, 41, 56, 44, 56, 3, 128, 40, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_3_130[] = {
	{1, 39, 6, 42, 6, 3, 131, 42, 55},
	{1, 41, 56, 44, 56, 3, 129, 40, 7},
	{2, 39, 7, 42, 7, 0, 0, 0, 0},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_3_131[] = {
	{1, 39, 6, 42, 6, 3, 132, 42, 55},
	{1, 41, 56, 44, 56, 3, 130, 40, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_3_132[] = {
	{1, 39, 6, 42, 6, 3, 133, 41, 55},
	{1, 41, 56, 44, 56, 3, 131, 40, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_3_133[] = {
	{1, 37, 56, 45, 56, 3, 132, 40, 7},
	{11, 40, 43, 40, 43, 101, 128, 101, 0},
	{3, 0, 0, 0, 0, 101, 902, 40, 43},
	{11, 41, 43, 41, 43, 102, 129, 102, 0},
	{3, 0, 0, 0, 0, 102, 902, 41, 43},
	{11, 42, 43, 42, 43, 103, 130, 103, 0},
	{3, 0, 0, 0, 0, 103, 902, 42, 43},
	{11, 43, 43, 43, 43, 104, 131, 104, 0},
	{3, 0, 0, 0, 0, 104, 902, 43, 43},
	{12, 41, 47, 41, 47, 100, 128, 100, 128},
	{3, 0, 0, 0, 0, 100, 900, 41, 47},
};

static const DragonLegacyTextEntry kDragonLegacyTexts_4[] = {
};

static const DragonLegacyObjectResource kDragonLegacyObjectResources_4[] = {
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_128[] = {
	{1, 9, 27, 9, 35, 101, 128, 0, 0},
	{3, 0, 0, 0, 0, 0, 129, 35, 0},
	{1, 74, 27, 74, 34, 4, 129, 10, 30},
	{1, 38, 56, 46, 56, 4, 130, 42, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_129[] = {
	{1, 9, 27, 9, 35, 4, 128, 73, 29},
	{3, 0, 0, 0, 0, 0, 129, 35, 0},
	{1, 74, 27, 74, 34, 1, 128, 10, 33},
	{1, 38, 56, 46, 56, 4, 131, 42, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_130[] = {
	{3, 0, 0, 0, 0, 0, 128, 0, 23},
	{1, 37, 6, 47, 6, 4, 128, 42, 55},
	{1, 74, 27, 74, 34, 4, 131, 10, 30},
	{1, 38, 56, 46, 56, 4, 135, 42, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_131[] = {
	{1, 9, 27, 9, 35, 4, 130, 73, 29},
	{1, 37, 6, 47, 6, 4, 129, 42, 55},
	{1, 74, 27, 74, 34, 4, 132, 10, 30},
	{1, 38, 56, 46, 56, 4, 136, 42, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_132[] = {
	{1, 9, 27, 9, 35, 4, 131, 73, 29},
	{1, 37, 6, 47, 6, 1, 128, 32, 36},
	{1, 74, 27, 74, 34, 4, 133, 10, 30},
	{1, 38, 56, 46, 56, 4, 137, 42, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_133[] = {
	{1, 9, 27, 9, 35, 4, 132, 73, 29},
	{3, 0, 0, 0, 0, 0, 129, 35, 0},
	{1, 74, 27, 74, 34, 4, 134, 10, 30},
	{1, 38, 56, 46, 56, 4, 138, 42, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_134[] = {
	{1, 9, 27, 9, 35, 4, 133, 73, 29},
	{3, 0, 0, 0, 0, 0, 129, 35, 0},
	{1, 74, 27, 74, 34, 100, 128, 0, 0},
	{1, 38, 56, 46, 56, 4, 139, 42, 7},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_135[] = {
	{3, 0, 0, 0, 0, 0, 128, 0, 23},
	{1, 37, 6, 47, 6, 4, 130, 42, 55},
	{1, 74, 27, 74, 34, 4, 136, 10, 30},
	{3, 0, 0, 0, 0, 0, 131, 37, 56},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_136[] = {
	{1, 9, 27, 9, 35, 4, 135, 73, 29},
	{1, 37, 6, 47, 6, 4, 131, 42, 55},
	{1, 74, 27, 74, 34, 4, 137, 10, 30},
	{1, 38, 56, 46, 56, 5, 128, 0, 0},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_137[] = {
	{1, 9, 27, 9, 35, 4, 136, 73, 29},
	{1, 37, 6, 47, 6, 4, 132, 42, 55},
	{1, 74, 27, 74, 34, 4, 138, 10, 30},
	{3, 0, 0, 0, 0, 0, 131, 37, 56},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_138[] = {
	{1, 9, 27, 9, 35, 4, 137, 73, 29},
	{1, 37, 6, 47, 6, 4, 133, 42, 55},
	{1, 74, 27, 74, 34, 4, 139, 10, 30},
	{3, 0, 0, 0, 0, 0, 131, 37, 56},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_4_139[] = {
	{1, 9, 27, 9, 35, 4, 138, 73, 29},
	{1, 37, 6, 47, 6, 4, 134, 42, 55},
	{3, 0, 0, 0, 0, 0, 130, 74, 20},
	{3, 0, 0, 0, 0, 0, 131, 37, 56},
};

static const DragonLegacyTextEntry kDragonLegacyTexts_1000[] = {
	{128, "Hello traveler.  Would you like to take a look at items I've come across?"},
	{129, "Very well.  How about a duel?  You against me.  Mono e mono."},
	{130, "I am very impressed.  Thank you.  Feel free to call on me whenever you like."},
};

static const DragonLegacyObjectResource kDragonLegacyObjectResources_1000[] = {
	{128, {10, 0, 0, 0, 0, 0, 128, 0, 0}},
	{129, {6, 0, 0, 0, 0, 0, 129, 130, 0}},
	{130, {12, 0, 0, 0, 0, 0, 149, 1000, 131}},
	{131, {5, 0, 0, 0, 0, 0, 130, 0, 0}},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_1000_128[] = {
	{1, 9, 28, 9, 35, 3, 128, 66, 41},
	{1, 74, 26, 74, 30, 1000, 129, 10, 32},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_1000_129[] = {
	{1, 9, 28, 9, 35, 1000, 128, 73, 28},
	{1, 74, 26, 74, 30, 1000, 130, 10, 32},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_1000_130[] = {
	{1, 9, 28, 9, 35, 1000, 129, 73, 28},
	{1, 74, 26, 74, 30, 1000, 131, 10, 32},
};

static const DragonLegacyMapObject kDragonLegacyMapObjects_1000_131[] = {
	{1, 9, 28, 9, 35, 1000, 130, 73, 28},
	{3, 0, 0, 0, 0, 0, 401, 71, 28},
	{3, 0, 0, 0, 0, 0, 401, 71, 30},
	{3, 0, 0, 0, 0, 0, 401, 72, 28},
	{3, 0, 0, 0, 0, 0, 401, 72, 30},
	{3, 0, 0, 0, 0, 0, 401, 73, 28},
	{3, 0, 0, 0, 0, 0, 401, 73, 30},
	{3, 0, 0, 0, 0, 0, 400, 73, 29},
	{6, 73, 29, 73, 29, 0, 128, 128, 0},
	{6, 73, 29, 73, 29, 1000, 128, 128, 129},
	{4, 71, 28, 73, 28, 0, 0, 0, 0},
	{4, 71, 30, 73, 30, 0, 0, 0, 0},
};

static const DragonLegacyMapScriptData kDragonLegacyMapScriptData[] = {
	{1, 128, "Eleusis", 33, kDragonLegacyMapObjects_1_128, 16, kDragonLegacyTexts_1, 4, kDragonLegacyObjectResources_1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0}},
	{1, 129, "Eleusis Stronghold", 25, kDragonLegacyMapObjects_1_129, 16, kDragonLegacyTexts_1, 4, kDragonLegacyObjectResources_1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0}},
	{2, 128, "Eleusis Caves", 15, kDragonLegacyMapObjects_2_128, 4, kDragonLegacyTexts_2, 4, kDragonLegacyObjectResources_2, {128, 128, 129, 130, 131, 131, 132, 133, 0, 0, 0, 0, 0, 0, 0, 0}, {134, 135, 134, 135}},
	{3, 128, "The Mountains", 4, kDragonLegacyMapObjects_3_128, 2, kDragonLegacyTexts_3, 3, kDragonLegacyObjectResources_3, {130, 130, 132, 132, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {138, 0, 0, 0}},
	{3, 129, "The Mountains", 2, kDragonLegacyMapObjects_3_129, 2, kDragonLegacyTexts_3, 3, kDragonLegacyObjectResources_3, {130, 130, 130, 131, 132, 132, 132, 133, 0, 0, 0, 0, 0, 0, 0, 0}, {138, 139, 0, 0}},
	{3, 130, "The Mountains", 3, kDragonLegacyMapObjects_3_130, 2, kDragonLegacyTexts_3, 3, kDragonLegacyObjectResources_3, {130, 131, 132, 133, 138, 138, 138, 139, 0, 0, 0, 0, 0, 0, 0, 0}, {134, 135, 141, 141}},
	{3, 131, "The Mountains", 2, kDragonLegacyMapObjects_3_131, 2, kDragonLegacyTexts_3, 3, kDragonLegacyObjectResources_3, {131, 133, 134, 135, 138, 139, 139, 140, 141, 132, 0, 0, 0, 0, 0, 0}, {136, 142, 143, 0}},
	{3, 132, "The Mountains", 2, kDragonLegacyMapObjects_3_132, 2, kDragonLegacyTexts_3, 3, kDragonLegacyObjectResources_3, {136, 136, 137, 137, 140, 140, 139, 141, 141, 141, 135, 136, 133, 131, 138, 139}, {142, 142, 143, 143}},
	{3, 133, "The Peak", 11, kDragonLegacyMapObjects_3_133, 2, kDragonLegacyTexts_3, 3, kDragonLegacyObjectResources_3, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {145, 144, 144, 142}},
	{4, 128, "The Forests", 4, kDragonLegacyMapObjects_4_128, 0, NULL, 0, NULL, {128, 129, 130, 131, 132, 133, 128, 129, 130, 131, 132, 133, 0, 0, 0, 0}, {139, 140, 0, 0}},
	{4, 129, "The Forests", 4, kDragonLegacyMapObjects_4_129, 0, NULL, 0, NULL, {128, 128, 128, 128, 134, 135, 137, 138, 129, 0, 0, 0, 0, 0, 0, 0}, {140, 139, 0, 0}},
	{4, 130, "The Forests", 4, kDragonLegacyMapObjects_4_130, 0, NULL, 0, NULL, {128, 128, 129, 129, 130, 131, 131, 132, 133, 0, 0, 0, 0, 0, 0, 0}, {139, 140, 0, 0}},
	{4, 131, "The Forests", 4, kDragonLegacyMapObjects_4_131, 0, NULL, 0, NULL, {128, 129, 130, 131, 132, 134, 135, 137, 138, 0, 0, 0, 0, 0, 0, 0}, {139, 140, 0, 0}},
	{4, 132, "The Forests", 4, kDragonLegacyMapObjects_4_132, 0, NULL, 0, NULL, {128, 128, 129, 134, 134, 135, 137, 138, 0, 0, 0, 0, 0, 0, 0, 0}, {139, 140, 0, 0}},
	{4, 133, "The Forests", 4, kDragonLegacyMapObjects_4_133, 0, NULL, 0, NULL, {128, 131, 132, 134, 134, 135, 135, 136, 137, 138, 0, 0, 0, 0, 0, 0}, {139, 140, 0, 0}},
	{4, 134, "The Forests", 4, kDragonLegacyMapObjects_4_134, 0, NULL, 0, NULL, {131, 132, 134, 135, 136, 137, 138, 137, 136, 0, 0, 0, 0, 0, 0, 0}, {139, 140, 0, 0}},
	{4, 135, "The Forests", 4, kDragonLegacyMapObjects_4_135, 0, NULL, 0, NULL, {130, 130, 131, 132, 133, 130, 133, 133, 0, 0, 0, 0, 0, 0, 0, 0}, {139, 140, 141, 0}},
	{4, 136, "The Forests", 4, kDragonLegacyMapObjects_4_136, 0, NULL, 0, NULL, {131, 132, 136, 136, 136, 134, 130, 135, 137, 138, 0, 0, 0, 0, 0, 0}, {139, 140, 141, 0}},
	{4, 137, "The Forests", 4, kDragonLegacyMapObjects_4_137, 0, NULL, 0, NULL, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {139, 140, 141, 139}},
	{4, 138, "The Forests", 4, kDragonLegacyMapObjects_4_138, 0, NULL, 0, NULL, {131, 132, 135, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {139, 140, 141, 139}},
	{4, 139, "The Forests", 4, kDragonLegacyMapObjects_4_139, 0, NULL, 0, NULL, {130, 130, 130, 130, 136, 136, 137, 138, 133, 133, 131, 138, 0, 0, 0, 0}, {139, 139, 140, 141}},
	{1000, 128, "The Meadows", 2, kDragonLegacyMapObjects_1000_128, 3, kDragonLegacyTexts_1000, 4, kDragonLegacyObjectResources_1000, {128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 0, 0, 0, 0, 0}, {0, 0, 0, 0}},
	{1000, 129, "The Meadows", 2, kDragonLegacyMapObjects_1000_129, 3, kDragonLegacyTexts_1000, 4, kDragonLegacyObjectResources_1000, {139, 140, 141, 142, 143, 144, 145, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0}},
	{1000, 130, "The Meadows", 2, kDragonLegacyMapObjects_1000_130, 3, kDragonLegacyTexts_1000, 4, kDragonLegacyObjectResources_1000, {128, 129, 130, 131, 132, 133, 142, 145, 136, 137, 138, 139, 140, 141, 143, 144}, {134, 135, 0, 0}},
	{1000, 131, "The Meadows", 12, kDragonLegacyMapObjects_1000_131, 3, kDragonLegacyTexts_1000, 4, kDragonLegacyObjectResources_1000, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {146, 147, 148, 0}},
};

static constexpr int kDragonLegacyMapScriptDataCount = 25;

static inline const DragonLegacyMapScriptData* DragonFindLegacyMapScriptData (uint16_t pluginId, uint16_t mapId) {
	for(int i = 0; i < kDragonLegacyMapScriptDataCount; i++) {
		if(kDragonLegacyMapScriptData[i].pluginId == pluginId and kDragonLegacyMapScriptData[i].mapId == mapId)
			return &kDragonLegacyMapScriptData[i];
	}
	return NULL;
}

static inline const DragonLegacyMapObject* DragonFindLegacyResourceObject (const DragonLegacyMapScriptData* mapData, uint16_t resourceId) {
	if(mapData == NULL or resourceId == 0)
		return NULL;
	for(int i = 0; i < mapData->objectResourceCount; i++) {
		if(mapData->objectResources[i].id == resourceId)
			return &mapData->objectResources[i].object;
	}
	return NULL;
}

static inline const char* DragonFindLegacyMapText (const DragonLegacyMapScriptData* mapData, uint16_t textId) {
	if(mapData == NULL or textId == 0)
		return NULL;
	for(int i = 0; i < mapData->textCount; i++) {
		if(mapData->texts[i].id == textId)
			return mapData->texts[i].text;
	}
	return NULL;
}

#endif // DRAGON_ALPHA_LEGACY_SCRIPT_DATA_GENERATED_H
