#ifndef DRAGON_ALPHA_LEGACY_WARP_DATA_GENERATED_H
#define DRAGON_ALPHA_LEGACY_WARP_DATA_GENERATED_H

// Auto-generated by Agents/GenerateLegacyWarpData.sh
// Source: Assets/Legacy/Data/Areas/*/Data (Map resources, warp objects only)

#include <stdint.h>

struct DragonLegacyWarpObject {
	uint16_t x1;
	uint16_t y1;
	uint16_t x2;
	uint16_t y2;
	uint16_t targetPluginId;
	uint16_t targetMapId;
	uint16_t targetX;
	uint16_t targetY;
};

struct DragonLegacyDirectionalWarp {
	uint16_t targetPluginId;
	uint16_t targetMapId;
	int16_t targetX;
	int16_t targetY;
	uint8_t active;
};

struct DragonLegacyMapWarpData {
	uint16_t pluginId;
	uint16_t mapId;
	const char* mapName;
	int warpCount;
	const DragonLegacyWarpObject* warps;
	DragonLegacyDirectionalWarp northWarp;
	DragonLegacyDirectionalWarp southWarp;
	DragonLegacyDirectionalWarp westWarp;
	DragonLegacyDirectionalWarp eastWarp;
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_1_128[] = {
	{25, 16, 25, 16, 1, 129, 12, 19},
	{38, 6, 46, 6, 3, 128, 42, 55},
	{9, 32, 9, 36, 4, 129, 73, 29},
	{30, 37, 33, 37, 4, 132, 42, 7},
	{79, 25, 79, 25, 2, 128, 63, 5},
	{19, 21, 19, 21, 1, 128, 5, 62},
	{5, 63, 5, 63, 1, 128, 19, 21},
	{15, 27, 15, 27, 1, 128, 25, 62},
	{25, 63, 52, 63, 1, 128, 15, 27},
	{25, 33, 25, 33, 1, 128, 47, 62},
	{47, 63, 47, 63, 1, 128, 25, 33},
	{38, 22, 38, 22, 1, 128, 69, 62},
	{69, 63, 69, 63, 1, 128, 38, 22},
	{38, 34, 38, 34, 1, 128, 79, 46},
	{79, 47, 79, 47, 1, 128, 38, 34},
	{49, 16, 49, 16, 1, 128, 79, 12},
	{78, 13, 80, 13, 1, 128, 48, 16},
	{79, 7, 79, 7, 1, 128, 78, 29},
	{78, 30, 78, 30, 1, 128, 79, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_1_129[] = {
	{11, 19, 13, 19, 1, 128, 25, 16},
	{5, 17, 5, 18, 2, 128, 3, 17},
	{20, 17, 20, 18, 2, 128, 22, 17},
	{23, 7, 23, 7, 1, 129, 81, 16},
	{81, 16, 81, 16, 1, 129, 23, 7},
	{81, 5, 81, 5, 1, 129, 23, 60},
	{23, 60, 23, 60, 1, 129, 81, 5},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_2_128[] = {
	{4, 17, 4, 18, 1, 129, 5, 17},
	{21, 17, 21, 18, 1, 129, 20, 17},
	{63, 4, 63, 4, 1, 128, 79, 25},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_3_128[] = {
	{39, 6, 42, 6, 3, 129, 42, 55},
	{41, 56, 44, 56, 1, 128, 42, 7},
	{67, 38, 67, 44, 1000, 128, 10, 32},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_3_129[] = {
	{39, 6, 42, 6, 3, 130, 42, 55},
	{41, 56, 44, 56, 3, 128, 40, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_3_130[] = {
	{39, 6, 42, 6, 3, 131, 42, 55},
	{41, 56, 44, 56, 3, 129, 40, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_3_131[] = {
	{39, 6, 42, 6, 3, 132, 42, 55},
	{41, 56, 44, 56, 3, 130, 40, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_3_132[] = {
	{39, 6, 42, 6, 3, 133, 41, 55},
	{41, 56, 44, 56, 3, 131, 40, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_3_133[] = {
	{37, 56, 45, 56, 3, 132, 40, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_128[] = {
	{9, 27, 9, 35, 101, 128, 0, 0},
	{74, 27, 74, 34, 4, 129, 10, 30},
	{38, 56, 46, 56, 4, 130, 42, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_129[] = {
	{9, 27, 9, 35, 4, 128, 73, 29},
	{74, 27, 74, 34, 1, 128, 10, 33},
	{38, 56, 46, 56, 4, 131, 42, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_130[] = {
	{37, 6, 47, 6, 4, 128, 42, 55},
	{74, 27, 74, 34, 4, 131, 10, 30},
	{38, 56, 46, 56, 4, 135, 42, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_131[] = {
	{9, 27, 9, 35, 4, 130, 73, 29},
	{37, 6, 47, 6, 4, 129, 42, 55},
	{74, 27, 74, 34, 4, 132, 10, 30},
	{38, 56, 46, 56, 4, 136, 42, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_132[] = {
	{9, 27, 9, 35, 4, 131, 73, 29},
	{37, 6, 47, 6, 1, 128, 32, 36},
	{74, 27, 74, 34, 4, 133, 10, 30},
	{38, 56, 46, 56, 4, 137, 42, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_133[] = {
	{9, 27, 9, 35, 4, 132, 73, 29},
	{74, 27, 74, 34, 4, 134, 10, 30},
	{38, 56, 46, 56, 4, 138, 42, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_134[] = {
	{9, 27, 9, 35, 4, 133, 73, 29},
	{74, 27, 74, 34, 100, 128, 0, 0},
	{38, 56, 46, 56, 4, 139, 42, 7},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_135[] = {
	{37, 6, 47, 6, 4, 130, 42, 55},
	{74, 27, 74, 34, 4, 136, 10, 30},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_136[] = {
	{9, 27, 9, 35, 4, 135, 73, 29},
	{37, 6, 47, 6, 4, 131, 42, 55},
	{74, 27, 74, 34, 4, 137, 10, 30},
	{38, 56, 46, 56, 5, 128, 0, 0},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_137[] = {
	{9, 27, 9, 35, 4, 136, 73, 29},
	{37, 6, 47, 6, 4, 132, 42, 55},
	{74, 27, 74, 34, 4, 138, 10, 30},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_138[] = {
	{9, 27, 9, 35, 4, 137, 73, 29},
	{37, 6, 47, 6, 4, 133, 42, 55},
	{74, 27, 74, 34, 4, 139, 10, 30},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_4_139[] = {
	{9, 27, 9, 35, 4, 138, 73, 29},
	{37, 6, 47, 6, 4, 134, 42, 55},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_1000_128[] = {
	{9, 28, 9, 35, 3, 128, 66, 41},
	{74, 26, 74, 30, 1000, 129, 10, 32},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_1000_129[] = {
	{9, 28, 9, 35, 1000, 128, 73, 28},
	{74, 26, 74, 30, 1000, 130, 10, 32},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_1000_130[] = {
	{9, 28, 9, 35, 1000, 129, 73, 28},
	{74, 26, 74, 30, 1000, 131, 10, 32},
};

static const DragonLegacyWarpObject kDragonLegacyWarpObjects_1000_131[] = {
	{9, 28, 9, 35, 1000, 130, 73, 28},
};

static const DragonLegacyMapWarpData kDragonLegacyMapWarpData[] = {
	{1, 128, "Eleusis", 19, kDragonLegacyWarpObjects_1_128, {0, 0, 0, 0, 0}, {1, 128, 15, 27, 1}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{1, 129, "Eleusis Stronghold", 7, kDragonLegacyWarpObjects_1_129, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{2, 128, "Eleusis Caves", 3, kDragonLegacyWarpObjects_2_128, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{3, 128, "The Mountains", 3, kDragonLegacyWarpObjects_3_128, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{3, 129, "The Mountains", 2, kDragonLegacyWarpObjects_3_129, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{3, 130, "The Mountains", 2, kDragonLegacyWarpObjects_3_130, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{3, 131, "The Mountains", 2, kDragonLegacyWarpObjects_3_131, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{3, 132, "The Mountains", 2, kDragonLegacyWarpObjects_3_132, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{3, 133, "The Peak", 1, kDragonLegacyWarpObjects_3_133, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 128, "The Forests", 3, kDragonLegacyWarpObjects_4_128, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 129, "The Forests", 3, kDragonLegacyWarpObjects_4_129, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 130, "The Forests", 3, kDragonLegacyWarpObjects_4_130, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 131, "The Forests", 4, kDragonLegacyWarpObjects_4_131, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 132, "The Forests", 4, kDragonLegacyWarpObjects_4_132, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 133, "The Forests", 3, kDragonLegacyWarpObjects_4_133, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 134, "The Forests", 3, kDragonLegacyWarpObjects_4_134, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 135, "The Forests", 2, kDragonLegacyWarpObjects_4_135, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 136, "The Forests", 4, kDragonLegacyWarpObjects_4_136, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 137, "The Forests", 3, kDragonLegacyWarpObjects_4_137, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 138, "The Forests", 3, kDragonLegacyWarpObjects_4_138, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{4, 139, "The Forests", 2, kDragonLegacyWarpObjects_4_139, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{1000, 128, "The Meadows", 2, kDragonLegacyWarpObjects_1000_128, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{1000, 129, "The Meadows", 2, kDragonLegacyWarpObjects_1000_129, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{1000, 130, "The Meadows", 2, kDragonLegacyWarpObjects_1000_130, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
	{1000, 131, "The Meadows", 1, kDragonLegacyWarpObjects_1000_131, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}, {0, 0, 0, 0, 0}},
};

static constexpr int kDragonLegacyMapWarpDataCount = 25;

static inline const DragonLegacyMapWarpData* DragonFindLegacyMapWarpData (uint16_t pluginId, uint16_t mapId) {
	for(int i = 0; i < kDragonLegacyMapWarpDataCount; i++) {
		if(kDragonLegacyMapWarpData[i].pluginId == pluginId and kDragonLegacyMapWarpData[i].mapId == mapId)
			return &kDragonLegacyMapWarpData[i];
	}
	return NULL;
}

#endif // DRAGON_ALPHA_LEGACY_WARP_DATA_GENERATED_H
